general.import = [
  "~/.config/alacritty/themes/themes/gnome_terminal.toml"
]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = false
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 15
